services:
  postgres:
    image: 'postgres:17'
    env_file: '.env'
    container_name: 'exam3-db'
    environment:
      - 'POSTGRES_DB=exam3'
      - 'POSTGRES_PASSWORD=5462432'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
